export const adminIds = ["114709955611509196686"]

export const initialTags = [
    "Java",
    "Python",
    "JavaScript",
    "React",
    "Node.js",
    "SQL",
    "MongoDB",
    "Git",
    "Linux",
    "HTML",
    "CSS",
    "Agile",
    "AWS",
    "TCP/IP",
    "Encryption",
    "Communication",
    "Problem-solving",
    "Teamwork",
    "Time Management",
    "Software-Developer",
    "Web Developer",
    "Front-End Development",
    "Back-end Development",
    "FullStack Developer",
    "HR Manager",
    "Data SCientis",
    "Graphic Desiner",
];

export const FilterData = [
    { id: "1", label: "Java", value: "Java" },
    { id: "2", label: "Python", value: "Python" },
    { id: "3", label: "JavaScript", value: "JavaScript" },
    { id: "4", label: "React", value: "React" },
    { id: "5", label: "Node.js", value: "Node.js" },
    { id: "6", label: "SQL", value: "SQL" },
    { id: "7", label: "MongoDB", value: "MongoDB" },
    { id: "8", label: "Git", value: "Git" },
    { id: "9", label: "Linux", value: "Linux" },
    { id: "10", label: "HTML", value: "HTML" },
    { id: "11", label: "CSS", value: "CSS" },
    { id: "12", label: "Agile", value: "Agile" },
    { id: "13", label: "AWS", value: "AWS" },
    { id: "14", label: "TCP/IP", value: "TCP/IP" },
    { id: "15", label: "Encryption", value: "Encryption" },
    { id: "16", label: "Communication", value: "Communication" },
    { id: "17", label: "Problem-solving", value: "Problem-solving" },
    { id: "18", label: "Teamwork", value: "Teamwork" },
    { id: "19", label: "Time Management", value: "Time Management" },
    { id: "20", label: "Software-Developer", value: "Software-Developer" },
    { id: "21", label: "Web Developer", value: "Web Developer" },
    { id: "22", label: "Front-End Development", value: "Front-End Development" },
    { id: "23", label: "Back-end Development", value: "Back-end Development" },
    { id: "24", label: "FullStack Developer", value: "FullStack Developer" },
    { id: "25", label: "HR Manager", value: "HR Manager" },
    { id: "26", label: "Data SCientis", value: "Data SCientis" },
    { id: "27", label: "Graphic Desiner", value: "Graphic Desiner" }
];


